In [9]:
import pandas as pd
import gseapy as gp
import os

In [4]:
signature = pd.read_csv('GSE115469.Non-immune_Separate_Signature.txt',delimiter='\t',index_col=0)
signature

,Central_venous_LSECs,Cholangiocytes,Other,Hepatocyte,Portal_endothelial_Cells,Periportal_LSECs,Hepatic_Stellate_Cells,Erythroid_Cells
NAME,,,,,,,,
A1BG,1.000000,1.000000,72.236321,845.303578,1.000000,1.000000,1.000000,48.535486
A1CF,1.000000,96.661956,1.000000,145.976036,1.000000,1.000000,1.000000,1.000000
A2M,1123.093023,1.000000,1.000000,449.784653,92.700137,579.211754,270.391612,1.000000
AADAC,1.000000,1.000000,1.000000,333.080404,1.000000,1.000000,1.000000,1.000000
AAK1,1.000000,1.000000,153.812318,1.000000,1.000000,121.833662,1.000000,1.000000
...,...,...,...,...,...,...,...,...
ZNF451,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,39.198593
ZNF593,1.000000,1.000000,1.000000,77.000386,1.000000,1.000000,1.000000,1.000000
ZNF706,1.000000,1.000000,104.483672,1.000000,1.000000,92.331445,1.000000,1.000000
ZNF90,1.000000,1.000000,76.835577,1.000000,1.000000,1.000000,1.000000,1.000000
ZSCAN16.AS1,1.000000,1.000000,1.000000,66.639515,1.000000,1.000000,1.000000,1.000000

In [6]:
cell_types = list(signature.columns.values)
cell_types

['Central_venous_LSECs',
 'Cholangiocytes',
 'Other',
 'Hepatocyte',
 'Portal_endothelial_Cells',
 'Periportal_LSECs',
 'Hepatic_Stellate_Cells',
 'Erythroid_Cells']

In [8]:
library = 'WikiPathway_2021_Human'

In [10]:
try:
    os.mkdir(library)
except:
    pass

for cell_type in cell_types:
    signature_matrix = signature.filter([cell_type])
    signature_matrix = signature_matrix[signature_matrix[cell_type] != 1]
    signature_gene_list = list(signature_matrix.index.values)
    enr = gp.enrichr(gene_list=signature_gene_list, gene_sets=library,
                 organism='Human', description='test_name',
                 outdir='%s/%s'%(library,cell_type),
                 # no_plot=True,
                 cutoff=0.5 # test dataset, use lower value from range(0,1)
                )

In [11]:
signature_matrix

         Central_venous_LSECs
NAME
A2M               1123.093023
ACAT1               96.506960
ACP5              1257.575013
ACSM3              187.598875
ACTB              3523.297652
...                       ...
YY1                141.934240
ZFP36              308.135430
ZFP36L1            638.303150
ZFP36L2            135.856990
ZNF207             133.151194

[755 rows x 1 columns]