In [1]:
import pandas as pd
import gseapy as gp
import os

In [2]:
signature = pd.read_csv('GSE115469.Immune_Separate_Signature.txt',delimiter='\t',index_col=0)
signature

,Other,Non-inflammatory_Macrophage,alpha-beta_T_Cells,Inflammatory_Macrophage,NK-like_Cells,gamma-delta_T_Cells,Mature_B_Cells,Plasma_Cells
NAME,,,,,,,,
A1CF,119.505186,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
A2M,480.677067,103.996742,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
AADAC,266.863274,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
AAK1,1.000000,1.000000,213.936872,92.248826,241.166358,230.704692,1.000000,1.000000
ABAT,88.616148,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...
ZNF593,67.849406,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,104.672768
ZNF706,1.000000,1.000000,1.000000,103.143826,71.718544,83.099235,168.569435,225.495629
ZNF90,1.000000,1.000000,97.659131,1.000000,1.000000,1.000000,143.276945,70.415591
ZSCAN16.AS1,64.154186,84.498925,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
ZYX,1.000000,1.000000,1.000000,158.158112,1.000000,1.000000,1.000000,1.000000

In [3]:
cell_types = list(signature.columns.values)
cell_types

['Other',
 'Non-inflammatory_Macrophage',
 'alpha-beta_T_Cells',
 'Inflammatory_Macrophage',
 'NK-like_Cells',
 'gamma-delta_T_Cells',
 'Mature_B_Cells',
 'Plasma_Cells']

In [4]:
library = 'WikiPathway_2021_Human'

In [5]:
try:
    os.mkdir(library)
except:
    pass

for cell_type in cell_types:
    signature_matrix = signature.filter([cell_type])
    signature_matrix = signature_matrix[signature_matrix[cell_type] != 1]
    signature_gene_list = list(signature_matrix.index.values)
    enr = gp.enrichr(gene_list=signature_gene_list, gene_sets=library,
                 organism='Human', description='test_name',
                 outdir='%s/%s'%(library,cell_type),
                 # no_plot=True,
                 cutoff=0.5 # test dataset, use lower value from range(0,1)
                )

In [6]:
signature_matrix

        Plasma_Cells
NAME
ABCB9      78.088249
ABRACL     68.464620
ACP1       88.759380
ADI1       80.534234
ADRM1      90.463341
...              ...
ZC3H13    134.204851
ZC3H15     84.070485
ZNF593    104.672768
ZNF706    225.495629
ZNF90      70.415591

[525 rows x 1 columns]